// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcsncpvikmfkeckwzmri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjc25jcHZpa21ma2Vja3d6bXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODkxOTcsImV4cCI6MjA2NDE2NTE5N30.JXyNwWhUB4X-d5OpGesu4Xa_h_0Fx6CuXeY-NDhGJ0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);